### ISSUE TITLE
Catalyst TODOs

### ISSUE THREAD

**Issue by MangoIV** [mlabs-haskell/cardano-open-oracle-protocol#3]
*This issue exists to maintain a list of tasks that have to be done to reach the goal defined in [the catalyst proposal](https://cardano.ideascale.com/c/idea/402572).*

**TODOs:**
- [ ] Investigate and test multiple Trx signatories flow
- [ ] create pure implementations for the proposed ideas
  - [ ] data registry
  - [x] #4
  - [ ] signature scheme
- [ ] create implementation for actual onchain and offchain
  - [x] cardano-transaction-lib vasil support https://github.com/Plutonomicon/cardano-transaction-lib/issues/379
  - [x] plutarch vasil support https://github.com/Plutonomicon/plutarch/issues/484
  - [ ] lucid vasil support ([see branch](https://github.com/Berry-Pool/lucid/tree/vasil) we have to decide on which of the two, `ctl` or `lucid`, we use)
  - [ ] transfer the pure implementaion to actual onchain and offchain implementations
  - [ ] show how communication with some API could be set up
- [ ] benchmarking of the different ideas
  - [ ] benchmarking for onchain data registry
  - [ ] benchmarking for signature scheme
  - [ ] benchmarking for commitment scheme
  - [ ] benchmarking for combinations of them
