### ISSUE TITLE
Cleanup tasks

### ISSUE THREAD

**Issue by bladyjoker** [mlabs-haskell/cardano-open-oracle-protocol#39]
TODO

- [x] Merge upstream mlabs-haskell/bot-plutus-interface 
  - STATUS: DONE
  - https://github.com/mlabs-haskell/bot-plutus-interface/pull/151
- [x] Merge upstream plutonomicon/plutarch
  - STATUS: DONE
  - https://github.com/Plutonomicon/plutarch-plutus/pull/573
- [ ] Merge upstream haskell-grpc-native/http2-grpc-haskell
  - STATUS: In progress
  - https://github.com/haskell-grpc-native/http2-grpc-haskell/pull/61
  - NOTE: Low priority
