### ISSUE TITLE
Tasks left

### ISSUE THREAD

**Issue by bladyjoker** [mlabs-haskell/cardano-open-oracle-protocol#43]
## TODO (ordered by priority)

- [x] Test `coop-plutus` with `plutarch-test` and integrate audit findings
  - **STATUS**: DONE
  - https://github.com/mlabs-haskell/cardano-open-oracle-protocol/issues/41
  - DURATION: 1.5 - 3 days
- [x] Implement missing service layer for Publisher, TransactionBuilder and Collector
  - **STATUS**: DONE
  - DURATION: 1.5 - 3 days
- [x] Document COOP
  - **STATUS**: TODO
  - DURATION: 0.5 - 2 days
- [x] Implement command line interface layer for COOP
  - **STATUS**: DONE
  - DURATION: 1 - 1.5 days
  - https://github.com/mlabs-haskell/cardano-open-oracle-protocol/pull/46
- [x] Implement `coop-plutus-json` encoding
  - **STATUS**: DONE
  - #38
  - DURATION: 1 - 2 days
 - [ ] COOP example project
   - **STATUS**: TODO
   - DURATION: 3 - 4 days
   
## Delegated
- [x] Support Vasil features offchain
  - **STATUS**: DONE
  - https://github.com/mlabs-haskell/cardano-open-oracle-protocol/issues/30
  - DURATION: 1.5 - 3 days
- [x] Adjust `bot-plutus-interface` to allow for partially signing finalized transactions
  - **STATUS**: DONE
  - DURATION: 1.5 - 3 days 
  - https://github.com/mlabs-haskell/bot-plutus-interface/issues/147
- [ ] Integrating changes to COOP dependencies back upstream
  - **STATUS**: In progress
  - #39
  - DURATION: 1 - 1.5 days
